### ISSUE TITLE
Usage of graft and Quetions in graft source code

### ISSUE THREAD

**Issue by 1ncludeSteven** [wimkeir/graft#1]
# Usage of graft
I found that when using graft init, we should provide the target directory and class path. However, It goes wrong when I provide these paths. How should I provide the path about code which will be analysed in graft. This is my input and corresponding files:
![image](https://user-images.githubusercontent.com/56500775/227720191-f127b48e-69c2-4917-8319-158cac3a33fa.png)
![image](https://user-images.githubusercontent.com/56500775/227720214-c98f30e2-615a-43ec-9b69-2615e8e4cb70.png)
![image](https://user-images.githubusercontent.com/56500775/227720883-9741ee16-3000-40f1-9b5c-18c08dd2fc2b.png)

# Questions in graft source code
When I try to undestand the source code of graft, I found that there is no graft.traversal.CpgTraversal and CpgTraversalSource, So it would go wrong in IntelliJ IDEA. And there is no usage of graft.travelsal.CpgTraversalDsl and CpgTraversalDsl. Could you tell me how does this project running succefully?
![image](https://user-images.githubusercontent.com/56500775/227720637-48a789f8-7c35-4753-b880-82eb5fcd9024.png)
![image](https://user-images.githubusercontent.com/56500775/227720660-3dd5f6af-1a0f-4020-b5ce-1bd28d2e8813.png)

I will appreciate to you very much for your responce at your earliest convience. Also, It's wonderful and kind of you if you can give me a sample project to run this analysis with graft!

**Comment by wimkeir** [comment]
Hi @1ncludeSteven ✌️ thanks for using Graft!

Your first issue is because Graft takes compiled Java bytecode as input (.class files) and not Java source code (.java files). You're using the `src` directory as your target but that would contain your source files, instead you should use your build output directory (depending on your IDE it's probably called something like `build`, `dist`, `out` etc.). Keep in mind that the compiled bytecode it might be one or two levels deep - you'll need to look for the directory with the same name as your root package and use that directory's _parent_ as the target.

As for the second issue, the `CpgTraversal` and `CpgTraversalSource` classes don't exist in the source code, rather they are generated from the source code in `CpgTraversalDsl` and `CpgTraversalSourceDsl` (that's what the `@GremlinDsl` annotation does). It's been many years since I've touched this project and I can't remember exactly how to get your IDE to recognise this, but I think it's performed as part of the Gradle build, so if you run `./gradlew build --clean` in your project root or do a Gradle sync in your IDE it should solve this.

Good luck and do let me know if you manage to come right! Also please remember to cite us if you're using this project for research purposes 😉 you can find the accompanying paper at https://doi.org/10.1145/3410886.3410901 if you don't have it already. We also welcome contributions, so if you're making improvements to the codebase or even documentation/running instructions, you're more than welcome to open a pull request 💪

**Comment by wimkeir** [comment]
I've taken a closer look at your first two screenshots now and I see you already know the location of your compiled bytecode directory - it's the path you're using as the classpath argument. If you use that same value as your target directory as well, you should be good 💪 

The target directory argument and classpath argument are usually the same for small projects. It's only in larger projects where you have dependencies on external libraries that you might need to append these to the classpath argument (in which case you'd simply use `<your-original-classpath>:library1.jar:library2.jar>` and so on.

**Comment by 1ncludeSteven** [comment]
Thank you for your kind help, I have ran this project succefully! And I have saw the `CpgTraversalSource` and `CpgTraversal` in the classes.
